version: '3.9'

services:

  web-server-apache-php:
    container_name: 'web-server-apache-php-${PROJECT_NAME}'
    build:
      dockerfile: .docker/Dockerfile-web-server-apache-php
      context: .
      args:
        PROJECT_PUBLIC_PATH: ${PROJECT_PUBLIC_PATH}
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - '.docker/conf/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './projects/${PROJECT_NAME}:/var/www/html'
    ports:
      - '80${PORT}:80'

  web-wordpress:
    container_name: 'web-wordpress-${PROJECT_NAME}'
    build:
      dockerfile: .docker/Dockerfile-web-wordpress
      context: .
    stdin_open: true
    tty: true
    environment:
      - WORDPRESS_DB_HOST=db-mysql
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=docker_password
      - WORDPRESS_DB_PASSWORD=docker_password
    volumes:
      - './projects/${PROJECT_NAME}:/var/www/html'
    ports:
      - '90${PORT}:80'

  nodejs:
    container_name: 'nodejs-${PROJECT_NAME}'
    build:
      dockerfile: .docker/Dockerfile-nodejs
      context: .
      args:
        PROJECT_PUBLIC_PATH: ${PROJECT_PUBLIC_PATH}
        NODEJS_VERSION: ${NODEJS_VERSION}
    volumes:
      - '.:/var/www/html'
    ports:
      - '70${PORT}:80'

  db-mysql:
    container_name: 'db-mysql-${PROJECT_NAME}'
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=docker_user
      - MYSQL_PASSWORD=docker_password
      - MYSQL_ROOT_PASSWORD=docker_password
    volumes:
      - db_data_mysql:/var/lib/mysql
    ports:
      - '61${PORT}:3306'

  web-phpmyadmin:
    container_name: 'web-phpmyadmin-${PROJECT_NAME}'
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db-mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1000M
    ports:
      - '51${PORT}:80'

  web-adminer:
    container_name: 'web-adminer-${PROJECT_NAME}'
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db-mysql
    ports:
      - '52${PORT}:8080'

  db-postgres:
    container_name: 'db-postgres-${PROJECT_NAME}'
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=docker_user
      - POSTGRES_PASSWORD=docker_password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db_data_postgres:/var/lib/postgresql/data
    ports:
      - '62${PORT}:5432'

  web-pgadmin:
    container_name: 'web-pgadmin-${PROJECT_NAME}'
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '53${PORT}:80'

  db-redis:
    container_name: 'db-redis-${PROJECT_NAME}'
    image: redis:latest
    ports:
      - '63${PORT}:6379'

#  mailhog:
#    image: 'mailhog/mailhog:latest'
#    ports:
#      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#    networks:
#      - sail

volumes:
  db_data_mysql:
    name: db_data_mysql
  db_data_postgres:
    name: db_data_postgres